// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6FeKyxhUQZVF3WGueHS8lShxHwJlKJHc',
    appId: '1:581669635479:web:34350ddc154ac8600630d2',
    messagingSenderId: '581669635479',
    projectId: 'homestay-b5e53',
    authDomain: 'homestay-b5e53.firebaseapp.com',
    storageBucket: 'homestay-b5e53.firebasestorage.app',
    measurementId: 'G-CWWRDQHHF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB15TC0mz_o9Lbkg60wcCc-vvtasg8eLNc',
    appId: '1:581669635479:android:e872a560e2c7fbdf0630d2',
    messagingSenderId: '581669635479',
    projectId: 'homestay-b5e53',
    storageBucket: 'homestay-b5e53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrR4UjUW7v0Slzbu7YyM1N7jUWvCB-eH8',
    appId: '1:581669635479:ios:e44913d0ca2cd9a40630d2',
    messagingSenderId: '581669635479',
    projectId: 'homestay-b5e53',
    storageBucket: 'homestay-b5e53.firebasestorage.app',
    iosBundleId: 'com.example.bookinghomestay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrR4UjUW7v0Slzbu7YyM1N7jUWvCB-eH8',
    appId: '1:581669635479:ios:e44913d0ca2cd9a40630d2',
    messagingSenderId: '581669635479',
    projectId: 'homestay-b5e53',
    storageBucket: 'homestay-b5e53.firebasestorage.app',
    iosBundleId: 'com.example.bookinghomestay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6FeKyxhUQZVF3WGueHS8lShxHwJlKJHc',
    appId: '1:581669635479:web:d2ad8b25d0cf05060630d2',
    messagingSenderId: '581669635479',
    projectId: 'homestay-b5e53',
    authDomain: 'homestay-b5e53.firebaseapp.com',
    storageBucket: 'homestay-b5e53.firebasestorage.app',
    measurementId: 'G-FXD4E0BYNJ',
  );
}
